"""rename department

Revision ID: 12c9b01f14f8
Revises: ff2639da23b9
Create Date: 2025-09-15 20:40:57.708957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12c9b01f14f8'
down_revision = 'ff2639da23b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
